name: Hola Mundo - GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar Cowasay
        run: npm install -g cowsay

      - name: Ejecutar Hola Mundo
        run: node app.js

      - name: Generar mensaje con Cowsay
        run: |
          cowsay "Hola Mundo desde GitHub Actions!" > cowsay.txt
          cat cowsay.txt

      - name: Enviar Cowasay a ntfy
        if: always()
        run: |
          curl \
            -H "Title: GitHub Actions - Cowasay" \
            -H "Priority: default" \
            -H "Tags: github,ci,cow" \
            -H "Content-Type: text/plain" \
            --data-binary "@cowsay.txt" \
            https://ntfy.sh/devops-itla